from tkinter import*
windom=Tk()
windom.title("Reindeer")
windom.geometry("300x75")
frame=Frame(windom,width=15)
frame.pack()
scrollbar=Scrollbar(frame,orient=VERTICAL)
scrollbar.pack(side="right",fill="y")
menu=StringVar()
menu.set(("Comet","Dancer","Dasher","Donder","Prancer"))
listbox=Listbox(frame,listvariable=menu,height=5,width=10,yscrollcommand=scrollbar.set)
listbox.pack(side="left",fill="y")
scrollbar.config(command=listbox.yview)
windom.mainloop()
